language: node_js
sudo: false
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jGD7p6O+fkl054+4sSfci7WbLoVXoHMhkxQKZ89Gexl/nmaEN6QJK/a+yVkKpDQEwX1GD1f3fS0TqOmkW0aOlpNY35VxZkD0kHqhpqaA4KCH6BdGrFMv/qfXoLiNy8dBfdSg3OaqxTjnIVMTKQzx1D1+BKj34xksD7fiRWwDmPY=
  file:
    - "spache-formula.js"
    - "spache-formula.min.js"
  on:
    tags: true
    node: '9.0'
